### ISSUE TITLE
Compat core is Null 1.20.1

### ISSUE THREAD

**Issue by border999** [CyberRat7/Extra_Compat#9] opened 2024-05-06 21:17 UTC
https://gist.github.com/border999/3049a216fa52f4f80d9ea4d689b34e01
Check near the bottom, downgrading to before 1.5.0 for now

**Comment by PeglinX** [comment] 2024-05-12 00:58
I have the same exact issue, thanks for the temporary solve

**Comment by AmazeingGames** [comment] 2024-05-21 05:26
Same here; it's crashed a few times and I'm somewhat sure issue this is the cause, as my [Latest.Log](https://gist.github.com/AmazeingGames/398c637b34dfbfd81ce07a33afd734c7) reads:
`Caused by: java.lang.NullPointerException: Cannot invoke "net.cyber_rat.extra_compat.core.CompatCore.addCreative(net.minecraftforge.event.BuildCreativeModeTabContentsEvent)" because "compatCore" is null`.

**Comment by CyberRat7** [comment] 2024-06-29 08:39
we are aware the newest version has many issues and are working on a fix please use an older version of the mod

**Comment by CyberRat7** [comment] 2024-06-30 16:35
Should be fixed in 1.5.3 make sure you are using Temporal Api 1.6.6

**Closed** 2024-07-14 21:24 UTC
